package configs

import "github.com/looplab/fsm"

var Lexicon = map[string]map[string]string{
	"response": {
		"start":                      "Hi! I need to access your Todoist account to get started. Please click here to sign in:\n%s",
		"already_authorized":         "You are already authorized!",
		"unknown_command":            "Please choose a command from the command list.",
		"new_task":                   "OK, a new task! At first, send me a name of the task",
		"enter_task_priority":        "Good! Now send me priority(from 1 to 4)",
		"enter_task_deadline":        "Nice, now send me due date",
		"enter_task_description":     "Finally send me task description",
		"add_task":                   "Success! Task added to your list",
		"task_list":                  "Here are your tasks!",
		"send_task_info":             "Task info: Name: %s Priority: %d Due date: %s Description: %s",
		"update_task":                "OK, what do you want to change?",
		"no_tasks":                   "Your task list is empty! To add tasks: /addtask",
		"help":                       "This bot is a client for Todoist service. It can add tasks, see your to-do lists, complete, delete and change tasks.",
		"enter_new_task_name":        "OK! Send me new task name",
		"enter_new_task_priority":    "OK! Send me new task priority",
		"enter_new_task_due_date":    "OK! Send me new task due date",
		"enter_new_task_description": "OK! Send me new task description",
	},
	"buttons": {
		"new_task":      "Add task 🧩",
		"today_tasks":   "Today tasks 📋",
		"all_tasks":     "All tasks 📝",
		"cancel":        "Cancel ❌",
		"skip":          "Skip ➡️",
		"complete_task": "Complete ✅",
		"update_task":   "Update",
		"delete_task":   "Delete ❌",
		"back":          "⬅️",
		"priority_1":    "1 🔴",
		"priority_2":    "2 🟠",
		"priority_3":    "3 🔵",
		"priority_4":    "4 ⚪",
		"today":         "Today",
		"tomorrow":      "Tomorrow",
		"next_week":     "Next week",
		"next_month":    "Next month",
		"name":          "Name",
		"priority":      "Priority",
		"due_date":      "Due date",
		"description":   "Description",
	},
}

var DatabaseRequests = map[string]string{
	"save": "INSERT INTO tokens(chat_id, access_token) VALUES (%d, '%s')",
	"get":  "SELECT access_token FROM tokens WHERE chat_id = %d",
}

var BotFSM = fsm.NewFSM(
	"default",
	fsm.Events{
		{Name: "root", Src: []string{"addTaskDescription",
			"addTaskName",
			"addTaskPriority",
			"addTaskDescription",
			"addTaskDeadline",
			"selectTask",
			"selectTodayTask",
			"selectedTodayTask",
		},
			Dst: "default",
		},
		{Name: "addTaskName", Src: []string{"default"}, Dst: "addTaskName"},
		{Name: "addTaskPriority", Src: []string{"addTaskName"}, Dst: "addTaskPriority"},
		{Name: "addTaskDeadline", Src: []string{"addTaskPriority"}, Dst: "addTaskDeadline"},
		{Name: "addTaskDescription", Src: []string{"addTaskDeadline"}, Dst: "addTaskDescription"},
		{Name: "selectTask", Src: []string{"default", "selectedTask", "selectTask", "updateTaskName", "updateTaskPriority", "updateTaskDueDate", "updateTaskDescription"}, Dst: "selectTask"},
		{Name: "selectTodayTask", Src: []string{"default", "selectedTodayTask", "selectTodayTask", "updateTodayTaskName", "updateTodayTaskPriority", "updateTodayTaskDueDate", "updateTodayTaskDescription"}, Dst: "selectTodayTask"},
		{Name: "selectedTask", Src: []string{"selectTask", "updateTask"}, Dst: "selectedTask"},
		{Name: "selectedTodayTask", Src: []string{"selectTodayTask", "updateTodayTask"}, Dst: "selectedTodayTask"},
		{Name: "updateTask", Src: []string{"selectedTask"}, Dst: "updateTask"},
		{Name: "updateTodayTask", Src: []string{"selectedTodayTask"}, Dst: "updateTodayTask"},
		{Name: "updateTaskName", Src: []string{"updateTask"}, Dst: "updateTaskName"},
		{Name: "updateTaskPriority", Src: []string{"updateTask"}, Dst: "updateTaskPriority"},
		{Name: "updateTaskDueDate", Src: []string{"updateTask"}, Dst: "updateTaskDueDate"},
		{Name: "updateTaskDescription", Src: []string{"updateTask"}, Dst: "updateTaskDescription"},
		{Name: "updateTodayTaskName", Src: []string{"updateTodayTask"}, Dst: "updateTodayTaskName"},
		{Name: "updateTodayTaskPriority", Src: []string{"updateTodayTask"}, Dst: "updateTodayTaskPriority"},
		{Name: "updateTodayTaskDueDate", Src: []string{"updateTodayTask"}, Dst: "updateTodayTaskDueDate"},
		{Name: "updateTodayTaskDescription", Src: []string{"updateTodayTask"}, Dst: "updateTodayTaskDescription"},
	},
	fsm.Callbacks{},
)
